<?php
$order = $block->getOrder();
if ($order->getState() == \Magento\Sales\Model\Order::STATE_CANCELED): ?>
    <button id="restore-order-button" title="Restore Order" type="button" class="action-default scalable">
        <span>Restore Order</span>
    </button>
    <script type="text/javascript">
        require([
            'jquery',
            'mage/url'
        ], function ($, urlBuilder) {
            $('#restore-order-button').on('click', function () {
                var restoreUrl = urlBuilder.build('restoreorder/order/restore/id/' + <?= $order->getId() ?>);
                window.location.href = restoreUrl;
            });
        });
    </script>
<?php endif; ?>
